<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BDJ - Syamsudin Noor_css-11aywtz r-13_61b320</name>
   <tag></tag>
   <elementGuidId>c4b56692-e478-4495-a09f-cd7fe9038253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1dbjc4n.r-kdyh1x.r-1p0dtai.r-1pi2tsx.r-1d2f490.r-1udh08x.r-105ug2t.r-zchlnj.r-ipm5af.r-13qz1uu > div.css-1dbjc4n.r-14lw9ot.r-1p0dtai.r-13awgt0.r-1pi2tsx.r-1d2f490.r-bnwqim.r-zchlnj.r-ipm5af.r-13qz1uu.r-184en5c > div.css-1dbjc4n.r-13awgt0 > div.css-1dbjc4n.r-1awozwy.r-2ndt7b.r-18u37iz.r-1iud8zs.r-f727ji > div.css-1dbjc4n.r-16y2uox.r-1wbh5a2 > div.css-1dbjc4n.r-1awozwy.r-18u37iz.r-1777fci.r-tuq35u > input.css-11aywtz.r-13awgt0.r-1sixt3s.r-1b43r93.r-135wba7.r-bcqeeo.r-1ny4l3l.r-10paoce.r-s1qlax.r-13n6l4s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Destination City</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>sentences</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-11aywtz r-13awgt0 r-1sixt3s r-1b43r93 r-135wba7 r-bcqeeo r-1ny4l3l r-10paoce r-s1qlax r-13n6l4s</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focusvisible-polyfill</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;css-1dbjc4n r-kdyh1x r-1p0dtai r-1pi2tsx r-1d2f490 r-1udh08x r-105ug2t r-zchlnj r-ipm5af r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-1p0dtai r-13awgt0 r-1pi2tsx r-1d2f490 r-bnwqim r-zchlnj r-ipm5af r-13qz1uu r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-13awgt0&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-2ndt7b r-18u37iz r-1iud8zs r-f727ji&quot;]/div[@class=&quot;css-1dbjc4n r-16y2uox r-1wbh5a2&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-18u37iz r-1777fci r-tuq35u&quot;]/input[@class=&quot;css-11aywtz r-13awgt0 r-1sixt3s r-1b43r93 r-135wba7 r-bcqeeo r-1ny4l3l r-10paoce r-s1qlax r-13n6l4s&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
