<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1da5d6fa-390e-4298-b3be-d591578942d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://d1785e74lyxkqq.cloudfront.net/_next/static/v2/5/53ba7ab2670984d89a61e056c97da92a.svg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1785e74lyxkqq.cloudfront.net/_next/static/v2/5/53ba7ab2670984d89a61e056c97da92a.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;css-1dbjc4n r-1p0dtai r-1pi2tsx r-1d2f490 r-105ug2t r-zchlnj r-ipm5af r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-1p0dtai r-1d2f490 r-u8s1d r-zchlnj r-13qz1uu r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-cqs64b&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz r-1wtj0ep r-ymttw5 r-1yzf0co&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-6cfva r-18kxxzh r-1q142lx&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-18u37iz r-msldlh r-1r5su4o&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-1jkjb&quot;]/div[@class=&quot;css-1dbjc4n r-z0gjz3 r-188shke r-1xss1fr r-14kuem7 r-1i6wzkk r-lrvibr&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d1785e74lyxkqq.cloudfront.net/_next/static/v2/5/53ba7ab2670984d89a61e056c97da92a.svg')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/img</value>
   </webElementXpaths>
</WebElementEntity>
